<?php

namespace AppBundle\Repository;

/**
 * tipoPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
